schema = 3

[mod]
  [mod.'atomicgo.dev/cursor']
    version = 'v0.2.0'
    hash = 'sha256-ukCb15fSgbkkYdzYY7dIq+HQqZvlpR5MytK20bwtSDc='

  [mod.'atomicgo.dev/keyboard']
    version = 'v0.2.9'
    hash = 'sha256-TqZY8yzAs9vEVR9dSi8yxBUIKPB875B2jl8fFGXQsCs='

  [mod.'atomicgo.dev/schedule']
    version = 'v0.1.0'
    hash = 'sha256-dBu76Ez+1S+koYL8KITrT/iEUN4U+8mk3BI/JZOr+Y8='

  [mod.'github.com/containerd/console']
    version = 'v1.0.5'
    hash = 'sha256-FY3+7lB6KmFEXHKtYZMwTraNkdYBRWTQXVHLwLED9Ys='

  [mod.'github.com/dustin/go-humanize']
    version = 'v1.0.1'
    hash = 'sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/gookit/color']
    version = 'v1.5.4'
    hash = 'sha256-6Xydefyslup+qohzatAdezGWrS065X5mx18wvRef3Rk='

  [mod.'github.com/lithammer/fuzzysearch']
    version = 'v1.1.8'
    hash = 'sha256-aMMRcrlUc9CBiiNkcnWWn4hfNMNyVhrAt67kvP4D4Do='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.16'
    hash = 'sha256-NC+ntvwIpqDNmXb7aixcg09il80ygq6JAnW0Gb5b/DQ='

  [mod.'github.com/mfridman/interpolate']
    version = 'v0.0.2'
    hash = 'sha256-3u04CYOy7PLMctdkum5pltSTkYya8EfXJexbW7j0KB8='

  [mod.'github.com/ncruces/go-strftime']
    version = 'v1.0.0'
    hash = 'sha256-GYIwYDONuv/yTE0AEugCHQbtV3oiBaco93xUNYFcVBQ='

  [mod.'github.com/pressly/goose/v3']
    version = 'v3.26.0'
    hash = 'sha256-3BoVYxB7n6wPiNuBNzCM8TTFFZE9/aaNM/IP+nLNK4Q='

  [mod.'github.com/pterm/pterm']
    version = 'v0.12.82'
    hash = 'sha256-rAOQkCP1FfKpVjfCZcDNZPUUz8XEjXFoChMP6LcIhzg='

  [mod.'github.com/remyoudompheng/bigfft']
    version = 'v0.0.0-20230129092748-24d4a6f8daec'
    hash = 'sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/rogpeppe/go-internal']
    version = 'v1.14.1'
    hash = 'sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E='

  [mod.'github.com/sethvargo/go-retry']
    version = 'v0.3.0'
    hash = 'sha256-1ZnFRHAaQjralGKVRoCbiwCXXB3w4kS3f+2hK9S8lbU='

  [mod.'github.com/urfave/cli/v3']
    version = 'v3.6.2'
    hash = 'sha256-GeTwfmXv2okvX2kmMREozvH4PH6ihPNVFSNSWrW+gyQ='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'go.uber.org/multierr']
    version = 'v1.11.0'
    hash = 'sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20251023183803-a4bb9ffd2546'
    hash = 'sha256-y0/A9UdtYNDlFglHQ7TW8ixSR2G36wHMRNc3sL7JXBY='

  [mod.'golang.org/x/sync']
    version = 'v0.17.0'
    hash = 'sha256-M85lz4hK3/fzmcUViAp/CowHSxnr3BHSO7pjHp1O6i0='

  [mod.'golang.org/x/sys']
    version = 'v0.40.0'
    hash = 'sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg='

  [mod.'golang.org/x/term']
    version = 'v0.32.0'
    hash = 'sha256-4cM/vhb8EUrlfHidBRfjYEQlUQehXiydJN77YkQvAic='

  [mod.'golang.org/x/text']
    version = 'v0.27.0'
    hash = 'sha256-VX0rOh6L3qIvquKSGjfZQFU8URNtGvkNvxE7OZtboW8='

  [mod.'golang.org/x/tools']
    version = 'v0.38.0'
    hash = 'sha256-GeIkpuKtUfxxrOZLikNlZA3lMKhdyO++PVvXppBGmbw='

  [mod.'modernc.org/libc']
    version = 'v1.67.6'
    hash = 'sha256-AmcruJSR6Rd6ORFKTm+xSB6G9aqW2dAw/+mWsG2FwcU='

  [mod.'modernc.org/mathutil']
    version = 'v1.7.1'
    hash = 'sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc='

  [mod.'modernc.org/memory']
    version = 'v1.11.0'
    hash = 'sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM='

  [mod.'modernc.org/sqlite']
    version = 'v1.45.0'
    hash = 'sha256-UlQBXU9v9lj6tmkmZU0wjuXpvkOubbgpFgBbgfWt4uQ='
